# Model arguments
model_name_or_path: HuggingFaceTB/SmolLM-135M-Instruct
model_revision: main
torch_dtype: bfloat16
# attn_implementation: flash_attention_2

# Data training arguments
dataset_name: HuggingFaceH4/Bespoke-Stratos-17k
dataset_configs:
- all
preprocessing_num_workers: 1

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
# eval_steps: 100
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: data/SmolLM-135M-Instruct-Open-R1-Distill
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1